// <auto-generated />
namespace Game_Store_Web_Front.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserIDAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserIDAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "201504261944433_UserID Add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
